#include "analysis.h"
#include "file_open_buffer.h"
#include "scanner_helper.h"
#include "tokenize.h"

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
    const char *filename = "file.txt";
    if (argc > 1)
    {
        filename = argv[1];
    }

    printf("Loading source file: %s\n", filename);
    char *buffer = read_file_ret_char_buffer(filename);
    if (buffer == NULL)
    {
        fprintf(stderr, "Error: Could not open or read file '%s'\n", filename);
        return 1;
    }

    // Step 1: Display token stream
    printf("\n--- Tokens Generated by Scanner ---\n");
    Scanner scanner;
    init_scanner(&scanner, buffer);

    while (1)
    {
        Token token = scan_token(&scanner);
        print_token(&token);
        if (token.type == TOKEN_EOF)
            break;
    }

    // Step 2: Run Statistical Analysis
    AnalysisStats stats;
    run_analysis_on_source(&stats, buffer);
    print_analysis_report(&stats);

    // Free loaded file buffer
    free(buffer);
    return 0;
}
